

# ==========================================
# TRANSLATIONS
# ==========================================
LANGUAGES = {
    "English": {
        "app_title": "MangaBuff Miner",
        "settings": "SETTINGS",
        "headless": "Headless Login",
        "controls": "CONTROLS",
        "btn_start": "🚀 START TURBO MINING",
        "btn_status": "📊 CHECK STATUS",
        "btn_stop": "🛑 STOP WORK",
        "btn_logout": "Sign Out / Change",
        "lbl_guest": "No Account",
        "timer_label": "NEXT RESET (MSK):",
        "log_title": "ACTIVITY LOG",
        "card_energy": "⚡ ENERGY",
        "card_balance": "💎 BALANCE",
        "login_title": "Account Login",
        "login_save": "Save & Login",
        "error_env": "Please log in first!",
        "error_fill": "Please fill all fields!",
        "log_login_start": "🚪 Logging in via Browser...",
        "log_process_login": "⏳ Processing Login...",
        "log_login_ok": "✅ Login successful!",
        "log_login_fail_page": "❌ Failed to reach Mining Page.",
        "log_login_fail_csrf": "❌ ERROR: CSRF Token missing.",
        "log_login_crash": "❌ Login Crash: {e}",
        "log_steal_keys": "🕵️ Stealing Session Keys...",
        "log_god_mode": "👻 Browser Closed. GOD MODE ACTIVE.",
        "log_mining_start": "🚀 STARTING API MINING...",
        "log_energy_empty": "🛑 Energy empty.",
        "log_mining_finish": "🏁 Session finished.",
        "log_logout": "ℹ️ Signed out.",
        "log_init": "🚀 Initializing...",
        "log_stopping": "🛑 Stopping...",
        "log_stat_energy": "⚡ Energy: {val}",
        "log_stat_balance": "💎 Balance: {val}",
        "log_session_load": "📂 Loading saved session...",
        "log_session_valid": "✅ Session valid!",
        "log_session_expired": "⚠️ Session expired. Re-logging...",
        "log_session_restart": "❌ Session likely expired. Restarting...",
        "log_upgrade_ok": "⬆️ UPGRADE SUCCESS! New Level.",
        "log_upgrade_fail": "⚠️ Upgrade failed or too expensive.",
        "log_upgrade_check": "🔍 Checking for upgrades...",
        "log_buy_upgrade": "💰 Buying upgrade for {price}...",
        "log_no_upgrade": "ℹ️ No upgrade found (Max Level?)",
        "log_upgrade_cost": "⬆️ Next Upgrade: {cost}",
        "log_upgrade_status_max": "⬆️ Upgrade: Max / None",
        "log_source_check": "🔍 Reading page source...",
        "log_done": "👋 Done.",
        "log_timeout": "⚠️ Timeout",
        "log_error_generic": "💥 Error: {e}",
        "log_thread_crash": "💥 Thread Crash: {e}"
    },
    "Русский": {
        "app_title": "MangaBuff Miner",
        "settings": "НАСТРОЙКИ",
        "headless": "Скрытый вход",
        "controls": "УПРАВЛЕНИЕ",
        "btn_start": "🚀 ТУРБО МАЙНИНГ",
        "btn_status": "📊 ПРОВЕРИТЬ СТАТУС",
        "btn_stop": "🛑 ОСТАНОВИТЬ",
        "btn_logout": "Выйти / Сменить",
        "lbl_guest": "Нет аккаунта",
        "timer_label": "СБРОС (МСК):",
        "log_title": "ЛОГ ДЕЙСТВИЙ",
        "card_energy": "⚡ ЭНЕРГИЯ",
        "card_balance": "💎 БАЛАНС",
        "login_title": "Вход в аккаунт",
        "login_save": "Сохранить и Войти",
        "error_env": "Сначала войдите в аккаунт!",
        "error_fill": "Заполните все поля!",
        "log_login_start": "🚪 Вход через браузер...",
        "log_process_login": "⏳ Обработка входа...",
        "log_login_ok": "✅ Успешный вход!",
        "log_login_fail_page": "❌ Не удалось открыть страницу.",
        "log_login_fail_csrf": "❌ ОШИБКА: Нет CSRF токена.",
        "log_login_crash": "❌ Ошибка входа: {e}",
        "log_steal_keys": "🕵️ Кража ключей сессии...",
        "log_god_mode": "👻 Браузер закрыт. GOD MODE АКТИВЕН.",
        "log_mining_start": "🚀 ЗАПУСК API ЦИКЛА...",
        "log_energy_empty": "🛑 Энергия закончилась.",
        "log_mining_finish": "🏁 Сессия завершена.",
        "log_logout": "ℹ️ Выход выполнен.",
        "log_init": "🚀 Инициализация...",
        "log_stopping": "🛑 Остановка...",
        "log_stat_energy": "⚡ Энергия: {val}",
        "log_stat_balance": "💎 Баланс: {val}",
        "log_session_load": "📂 Загрузка сессии...",
        "log_session_valid": "✅ Сессия активна!",
        "log_session_expired": "⚠️ Сессия истекла. Перезаходим...",
        "log_session_restart": "❌ Сессия истекла. Перезапуск...",
        "log_upgrade_ok": "⬆️ УЛУЧШЕНИЕ КУПЛЕНО! Новый уровень.",
        "log_upgrade_fail": "⚠️ Не хватает денег на улучшение.",
        "log_upgrade_check": "🔍 Проверка улучшений...",
        "log_buy_upgrade": "💰 Покупка улучшения за {price}...",
        "log_no_upgrade": "ℹ️ Улучшений нет (Макс. уровень?)",
        "log_upgrade_cost": "⬆️ След. уровень: {cost}",
        "log_upgrade_status_max": "⬆️ Улучшение: Макс / Нет",
        "log_source_check": "🔍 Чтение исходного кода...",
        "log_done": "👋 Готово.",
        "log_timeout": "⚠️ Тайм-аут соединения",
        "log_error_generic": "💥 Ошибка: {e}",
        "log_thread_crash": "💥 Крах потока: {e}"
    },
    "Українська": {
        "app_title": "MangaBuff Miner",
        "settings": "НАЛАШТУВАННЯ",
        "headless": "Прихований вхід",
        "controls": "КЕРУВАННЯ",
        "btn_start": "🚀 ТУРБО МАЙНІНГ",
        "btn_status": "📊 ПЕРЕВІРИТИ СТАТУС",
        "btn_stop": "🛑 ЗУПИНИТИ",
        "btn_logout": "Вийти / Змінити",
        "lbl_guest": "Немає акаунту",
        "timer_label": "СКИДАННЯ (МСК):",
        "log_title": "ЛОГ ДІЙ",
        "card_energy": "⚡ ЕНЕРГІЯ",
        "card_balance": "💎 БАЛАНС",
        "login_title": "Вхід в акаунт",
        "login_save": "Зберегти та Увійти",
        "error_env": "Спочатку увійдіть в акаунт!",
        "error_fill": "Заповніть усі поля!",
        "log_login_start": "🚪 Вхід через браузер...",
        "log_process_login": "⏳ Обробка входу...",
        "log_login_ok": "✅ Успішний вхід!",
        "log_login_fail_page": "❌ Не вдалося відкрити сторінку.",
        "log_login_fail_csrf": "❌ ПОМИЛКА: Немає CSRF токена.",
        "log_login_crash": "❌ Помилка входу: {e}",
        "log_steal_keys": "🕵️ Крадіжка ключів сесії...",
        "log_god_mode": "👻 Браузер закрито. GOD MODE АКТИВНИЙ.",
        "log_mining_start": "🚀 ЗАПУСК API ЦИКЛУ...",
        "log_energy_empty": "🛑 Енергія закінчилася.",
        "log_mining_finish": "🏁 Сесію завершено.",
        "log_logout": "ℹ️ Вихід виконано.",
        "log_init": "🚀 Ініціалізація...",
        "log_stopping": "🛑 Зупинка...",
        "log_stat_energy": "⚡ Енергія: {val}",
        "log_stat_balance": "💎 Баланс: {val}",
        "log_session_load": "📂 Завантаження сесії...",
        "log_session_valid": "✅ Сесія активна!",
        "log_session_expired": "⚠️ Сесія вичерпана. Перезаходимо...",
        "log_session_restart": "❌ Сесія вичерпана. Перезапуск...",
        "log_upgrade_ok": "⬆️ ПОКРАЩЕННЯ КУПЛЕНО! Новий рівень.",
        "log_upgrade_fail": "⚠️ Не вистачає грошей на покращення.",
        "log_upgrade_check": "🔍 Перевірка покращень...",
        "log_buy_upgrade": "💰 Купівля покращення за {price}...",
        "log_no_upgrade": "ℹ️ Покращень немає (Макс?)",
        "log_upgrade_cost": "⬆️ Наст. рівень: {cost}",
        "log_upgrade_status_max": "⬆️ Покращення: Макс / Немає",
        "log_source_check": "🔍 Читання вихідного коду...",
        "log_done": "👋 Готово.",
        "log_timeout": "⚠️ Тайм-аут з'єднання",
        "log_error_generic": "💥 Помилка: {e}",
        "log_thread_crash": "💥 Крах потоку: {e}"
    }
}

CURRENT_LANG = "English"

def tr(key, **kwargs):
    lang_dict = LANGUAGES.get(CURRENT_LANG, LANGUAGES["English"])
    text = lang_dict.get(key, LANGUAGES["English"].get(key, key))
    if kwargs: return text.format(**kwargs)
    return text