

# ==========================================
# TRANSLATIONS
# ==========================================
LANGUAGES = {
    "English": {
        "app_title": "MangaBuff Miner",
        "settings": "SETTINGS",
        "headless": "Headless Login",
        "controls": "CONTROLS",
        "btn_start": "🚀 START TURBO MINING",
        "btn_status": "📊 CHECK STATUS",
        "btn_stop": "🛑 STOP WORK",
        "btn_logout": "Sign Out / Change",
        "lbl_guest": "No Account",
        "timer_label": "NEXT RESET (MSK):",
        "log_title": "ACTIVITY LOG",
        "card_energy": "⚡ ENERGY",
        "card_balance": "💎 BALANCE",
        "login_title": "Account Login",
        "login_save": "Save & Login",
        "error_env": "Please log in first!",
        "error_fill": "Please fill all fields!",
        "log_login_start": "🚪 Logging in via Browser...",
        "log_process_login": "⏳ Processing Login...",
        "log_login_ok": "✅ Login successful!",
        "log_login_fail_page": "❌ Failed to reach Mining Page.",
        "log_login_fail_csrf": "❌ ERROR: CSRF Token missing.",
        "log_login_crash": "❌ Login Crash: {e}",
        "log_steal_keys": "🕵️ Stealing Session Keys...",
        "log_mining_start": "🚀 STARTING API MINING...",
        "log_startup_header": "🚀 Starting session:\n",
        "log_farm_start": "🪓Starting farming battles...",
        "log_mining_summary": "⛏️ Mining Summary: {clicks} clicks, {added} ore.",
        "log_energy_empty": "🛑 Energy empty.",
        "log_mining_finish": "🏁 Session finished.",
        "log_logout": "ℹ️ Signed out.",
        "log_init": "🚀 Initializing...",
        "log_stopping": "🛑 Stopping...",
        "log_stat_energy": "⚡ Energy: {val}",
        "log_stat_balance": "💎 Balance: {val}",
        "log_session_load": "📂 Loading saved session...",
        "log_session_valid": "✅ Session valid!",
        "log_session_expired": "⚠️ Session expired. Re-logging...",
        "log_session_restart": "❌ Session likely expired. Restarting...",
        "log_upgrade_ok": "⬆️ UPGRADE SUCCESS! New Level.",
        "log_upgrade_fail": "⚠️ Upgrade failed or too expensive.",
        "log_upgrade_check": "🔍 Checking for upgrades...",
        "log_buy_upgrade": "💰 Buying upgrade for {price}...",
        "log_no_upgrade": "ℹ️ No upgrade found (Max Level?)",
        "log_upgrade_cost": "⬆️ Next Upgrade: {cost}",
        "log_upgrade_status_max": "⬆️ Upgrade: Max / None",
        "log_source_check": "🔍 Reading page source...",
        "log_done": "👋 Done.",
        "log_timeout": "⚠️ Timeout",
        "log_error_generic": "💥 Error: {e}",
        "log_thread_crash": "💥 Thread Crash: {e}",
        "tg_settings": "TELEGRAM",
        "btn_test_tg": "🔔 TEST TG",
        "auto_upgrade": "Auto-upgrade Pickaxe",
        "tower_enabled": "Abyss Tower Expeditions",
        "log_quests_claimed": "📋 Quests claimed: {count}",
        "log_strong_hit_ok": "⚡ Strong Hit purchased!",
        "log_jackpot": "🔥 JACKPOT! Dropped card with tier {rarity}!",
        "log_turnstile_detected": "⚠️ Cloudflare Turnstile captcha detected! Complete it in browser.",
        "log_battle_summary": "⚔️ Battles: {done} | W: {wins} | L: {losses} | +{essence} essence",
        "log_tower_check": "🏰 Checking Abyss Tower expeditions...",
        "log_tower_claimed": "🎁 Tower expedition rewards claimed: +{diamonds} 💎, +{crystals} crystals!",
        "log_tower_started": "⚔️ Started Abyss Tower expedition ({diff}, {dur}h)",
        "log_tower_running": "⏳ Tower expedition active ({left} remaining)",
        "ads_enabled": "Daily Ads (+21 💎)",
        "quiz_enabled": "Daily Quiz (10 streak)",
        "reading_enabled": "Read Manga Chapters",
        "reading_limit": "Chapters per run:",
        "log_ads_check": "📺 Checking daily ads (3x7 💎)...",
        "log_ads_watched": "📺 Watched {count} ads (+{diamonds} 💎)",
        "log_ads_already": "ℹ️ Daily ads already completed (3/3).",
        "log_quiz_check": "🧩 Starting daily quiz (target: 10 correct)...",
        "log_quiz_done": "🧩 Quiz reward claimed! Streak: {count}. {detail}",
        "log_quiz_already": "ℹ️ Daily quiz already completed today.",
        "log_reading_check": "📖 Checking manga reading status...",
        "log_reading_batch": "📖 Read {count} chapters ({current}/{total})",
        "log_reading_card": "🎁 Bonus card dropped: {name}!",
        "log_reading_scroll": "📜 Sharpening scroll dropped: {name}!",
        "log_reading_summary": "📖 Reading finished: {chapters} chapters read, {cards} cards found.",
        "log_reading_limit_reached": "ℹ️ Daily reading limit reached ({chapters}/75 chapters, {cards}/10 cards).",
        "reading_wait_card_cd": "Stop reading on card cooldown"
    },
    "Русский": {
        "app_title": "MangaBuff Miner",
        "settings": "НАСТРОЙКИ",
        "headless": "Скрытый вход",
        "controls": "УПРАВЛЕНИЕ",
        "btn_start": "🚀 ТУРБО МАЙНИНГ",
        "btn_status": "📊 ПРОВЕРИТЬ СТАТУС",
        "btn_stop": "🛑 ОСТАНОВИТЬ",
        "btn_logout": "Выйти / Сменить",
        "lbl_guest": "Нет аккаунта",
        "timer_label": "СБРОС (МСК):",
        "log_title": "ЛОГ ДЕЙСТВИЙ",
        "card_energy": "⚡ ЭНЕРГИЯ",
        "card_balance": "💎 БАЛАНС",
        "login_title": "Вход в аккаунт",
        "login_save": "Сохранить и Войти",
        "error_env": "Сначала войдите в аккаунт!",
        "error_fill": "Заполните все поля!",
        "log_login_start": "🚪 Вход через браузер...",
        "log_process_login": "⏳ Обработка входа...",
        "log_login_ok": "✅ Успешный вход!",
        "log_login_fail_page": "❌ Не удалось открыть страницу.",
        "log_login_fail_csrf": "❌ ОШИБКА: Нет CSRF токена.",
        "log_login_crash": "❌ Ошибка входа: {e}",
        "log_steal_keys": "🕵️ Кража ключей сессии...",
        "log_mining_start": "🚀 ЗАПУСК API ЦИКЛА...",
        "log_energy_empty": "🛑 Энергия закончилась.",
        "log_mining_finish": "🏁 Сессия завершена.",
        "log_logout": "ℹ️ Выход выполнен.",
        "log_init": "🚀 Инициализация...",
        "log_stopping": "🛑 Остановка...",
        "log_stat_energy": "⚡ Энергия: {val}",
        "log_stat_balance": "💎 Баланс: {val}",
        "log_session_load": "📂 Загрузка сессии...",
        "log_session_valid": "✅ Сессия активна!",
        "log_session_expired": "⚠️ Сессия истекла. Перезаходим...",
        "log_session_restart": "❌ Сессия истекла. Перезапуск...",
        "log_upgrade_ok": "⬆️ УЛУЧШЕНИЕ КУПЛЕНО! Новый уровень.",
        "log_upgrade_fail": "⚠️ Не хватает денег на улучшение.",
        "log_upgrade_check": "🔍 Проверка улучшений...",
        "log_buy_upgrade": "💰 Покупка улучшения за {price}...",
        "log_no_upgrade": "ℹ️ Улучшений нет (Макс. уровень?)",
        "log_upgrade_cost": "⬆️ След. уровень: {cost}",
        "log_upgrade_status_max": "⬆️ Улучшение: Макс / Нет",
        "log_source_check": "🔍 Чтение исходного кода...",
        "log_done": "👋 Готово.",
        "log_timeout": "⚠️ Тайм-аут соединения",
        "log_error_generic": "💥 Ошибка: {e}",
        "log_thread_crash": "💥 Крах потока: {e}",
        "tg_settings": "TELEGRAM",
        "btn_test_tg": "🔔 ТЕСТ TG",
        "auto_upgrade": "Авто-апгрейд кирки",
        "tower_enabled": "Экспедиции Башни Разлома",
        "log_quests_claimed": "📋 Получено квестов: {count}",
        "log_strong_hit_ok": "⚡ «Сильный удар» куплен!",
        "log_jackpot": "🔥 ДЖЕКПОТ! Выпала карта с рангом {rarity}!",
        "log_turnstile_detected": "⚠️ Обнаружена капча Cloudflare Turnstile! Пройдите её в браузере.",
        "log_battle_summary": "⚔️ Бои: {done} | В: {wins} | П: {losses} | +{essence} эссенции",
        "log_tower_check": "🏰 Проверка экспедиций Башни Разлома...",
        "log_tower_claimed": "🎁 Получены награды Башни: +{diamonds} 💎, +{crystals} кристаллов!",
        "log_tower_started": "⚔️ Отправлена экспедиция Башни ({diff}, {dur}ч)",
        "log_tower_running": "⏳ Экспедиция Башни активна (осталось {left})",
        "ads_enabled": "Смотреть рекламу (+21 💎)",
        "quiz_enabled": "Ежедневный квиз (10 верных)",
        "reading_enabled": "Читать главы манги",
        "reading_limit": "Глав за запуск:",
        "log_ads_check": "📺 Проверка ежедневной рекламы (3x7 💎)...",
        "log_ads_watched": "📺 Просмотрено {count} рекламы (+{diamonds} 💎)",
        "log_ads_already": "ℹ️ Реклама на сегодня уже просмотрена (3/3).",
        "log_quiz_check": "🧩 Запуск ежедневного квиза (цель: 10 верных)...",
        "log_quiz_done": "🧩 Награда за квиз получена! Серия: {count}. {detail}",
        "log_quiz_already": "ℹ️ Ежедневный квиз на сегодня уже пройден.",
        "log_reading_check": "📖 Проверка статуса чтения глав...",
        "log_reading_batch": "📖 Прочитано {count} глав ({current}/{total})",
        "log_reading_card": "🎁 Выпала бонусная карта: {name}!",
        "log_reading_scroll": "📜 Выпал свиток заточки: {name}!",
        "log_reading_summary": "📖 Чтение завершено: прочитано {chapters} глав, найдено {cards} карт.",
        "log_reading_limit_reached": "ℹ️ Дневной лимит чтения достигнут ({chapters}/75 глав, {cards}/10 карт).",
        "reading_wait_card_cd": "Останавливать при кд карт"
    },
    "Українська": {
        "app_title": "MangaBuff Miner",
        "settings": "НАЛАШТУВАННЯ",
        "headless": "Прихований вхід",
        "controls": "КЕРУВАННЯ",
        "btn_start": "🚀 ТУРБО МАЙНІНГ",
        "btn_status": "📊 ПЕРЕВІРИТИ СТАТУС",
        "btn_stop": "🛑 ЗУПИНИТИ",
        "btn_logout": "Вийти / Змінити",
        "lbl_guest": "Немає акаунту",
        "timer_label": "СКИДАННЯ (МСК):",
        "log_title": "ЛОГ ДІЙ",
        "card_energy": "⚡ ЕНЕРГІЯ",
        "card_balance": "💎 БАЛАНС",
        "login_title": "Вхід в акаунт",
        "login_save": "Зберегти та Увійти",
        "error_env": "Спочатку увійдіть в акаунт!",
        "error_fill": "Заповніть усі поля!",
        "log_login_start": "🚪 Вхід через браузер...",
        "log_process_login": "⏳ Обробка входу...",
        "log_login_ok": "✅ Успішний вхід!",
        "log_login_fail_page": "❌ Не вдалося відкрити сторінку.",
        "log_login_fail_csrf": "❌ ПОМИЛКА: Немає CSRF токена.",
        "log_login_crash": "❌ Помилка входу: {e}",
        "log_steal_keys": "🕵️ Крадіжка ключів сесії...",
        "log_mining_start": "🚀 ЗАПУСК API ЦИКЛУ...",
        "log_energy_empty": "🛑 Енергія закінчилася.",
        "log_mining_finish": "🏁 Сесію завершено.",
        "log_logout": "ℹ️ Вихід виконано.",
        "log_init": "🚀 Ініціалізація...",
        "log_stopping": "🛑 Зупинка...",
        "log_stat_energy": "⚡ Енергія: {val}",
        "log_stat_balance": "💎 Баланс: {val}",
        "log_session_load": "📂 Завантаження сесії...",
        "log_session_valid": "✅ Сесія активна!",
        "log_session_expired": "⚠️ Сесія вичерпана. Перезаходимо...",
        "log_session_restart": "❌ Сесія вичерпана. Перезапуск...",
        "log_upgrade_ok": "⬆️ ПОКРАЩЕННЯ КУПЛЕНО! Новий рівень.",
        "log_upgrade_fail": "⚠️ Не вистачає грошей на покращення.",
        "log_upgrade_check": "🔍 Перевірка покращень...",
        "log_buy_upgrade": "💰 Купівля покращення за {price}...",
        "log_no_upgrade": "ℹ️ Покращень немає (Макс?)",
        "log_upgrade_cost": "⬆️ Наст. рівень: {cost}",
        "log_upgrade_status_max": "⬆️ Покращення: Макс / Немає",
        "log_source_check": "🔍 Читання вихідного коду...",
        "log_done": "👋 Готово.",
        "log_timeout": "⚠️ Тайм-аут з'єднання",
        "log_error_generic": "💥 Помилка: {e}",
        "log_thread_crash": "💥 Крах потоку: {e}",
        "tg_settings": "TELEGRAM",
        "btn_test_tg": "🔔 ТЕСТ TG",
        "auto_upgrade": "Авто-апгрейд кайла",
        "tower_enabled": "Експедиції Вежі Розлому",
        "log_quests_claimed": "📋 Отримано квестів: {count}",
        "log_strong_hit_ok": "⚡ «Сильний удар» куплено!",
        "log_jackpot": "🔥 ДЖЕКПОТ! Випала карта з рангом {rarity}!",
        "log_turnstile_detected": "⚠️ Виявлено капчу Cloudflare Turnstile! Пройдіть її у браузері.",
        "log_battle_summary": "⚔️ Бої: {done} | В: {wins} | П: {losses} | +{essence} есенції",
        "log_tower_check": "🏰 Перевірка експедицій Вежі Розлому...",
        "log_tower_claimed": "🎁 Отримано нагороди Вежі: +{diamonds} 💎, +{crystals} кристалів!",
        "log_tower_started": "⚔️ Відправлено експедицію Вежі ({diff}, {dur}год)",
        "log_tower_running": "⏳ Експедиція Вежі триває (залишилось {left})",
        "ads_enabled": "Дивитися рекламу (+21 💎)",
        "quiz_enabled": "Щоденний квіз (10 вірних)",
        "reading_enabled": "Читати розділи манги",
        "reading_limit": "Розділів за запуск:",
        "log_ads_check": "📺 Перевірка щоденної реклами (3x7 💎)...",
        "log_ads_watched": "📺 Переглянуто {count} реклами (+{diamonds} 💎)",
        "log_ads_already": "ℹ️ Рекламу на сьогодні вже переглянуто (3/3).",
        "log_quiz_check": "🧩 Запуск щоденного квізу (ціль: 10 вірних)...",
        "log_quiz_done": "🧩 Нагороду за квіз отримано! Серія: {count}. {detail}",
        "log_quiz_already": "ℹ️ Щоденний квіз на сьогодні вже пройдено.",
        "log_reading_check": "📖 Перевірка статусу читання розділів...",
        "log_reading_batch": "📖 Прочитано {count} розділів ({current}/{total})",
        "log_reading_card": "🎁 Випала бонусна карта: {name}!",
        "log_reading_scroll": "📜 Випав сувій заточування: {name}!",
        "log_reading_summary": "📖 Читання завершено: прочитано {chapters} розділів, знайдено {cards} карт.",
        "log_reading_limit_reached": "ℹ️ Щоденний ліміт читання вичерпано ({chapters}/75 розділів, {cards}/10 карт).",
        "reading_wait_card_cd": "Зупиняти при кд карт"
    }
}

CURRENT_LANG = "English"

def tr(key, **kwargs):
    lang_dict = LANGUAGES.get(CURRENT_LANG, LANGUAGES["English"])
    text = lang_dict.get(key, LANGUAGES["English"].get(key, key))
    if kwargs: return text.format(**kwargs)
    return text